# Generated by Django 5.1.2 on 2024-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувача', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(default=1, max_length=10, verbose_name='Ідентифікаційний код'),
            preserve_default=False,
        ),
    ]
