# Generated by Django 4.2.7 on 2024-08-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrgrupp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Група контрагентів',
                'verbose_name_plural': 'Групи контрагентів',
                'db_table': 'contrgrupp',
            },
        ),
        migrations.CreateModel(
            name='Counterparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=800, verbose_name='Повна назва')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('adres', models.CharField(blank=True, max_length=800, verbose_name='Адреса')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Країна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('street', models.CharField(blank=True, max_length=300, verbose_name='Вулиця')),
                ('number', models.CharField(blank=True, max_length=8, verbose_name='Номер будинку')),
                ('letter', models.CharField(blank=True, max_length=2, verbose_name='Дріб')),
                ('okpo_cod', models.CharField(blank=True, max_length=10, verbose_name='Код ЄДРПОУ')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ІПН')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Керівник')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
                'db_table': 'counterpart',
            },
        ),
        migrations.CreateModel(
            name='licenss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True, verbose_name='guid')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('data_po', models.DateTimeField(blank=True, verbose_name='Ліцензія діє по')),
                ('okpo', models.CharField(max_length=10, verbose_name='okpo')),
            ],
            options={
                'verbose_name': 'Ліцензія',
                'verbose_name_plural': 'Ліцензії',
                'db_table': 'licenss',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=150, verbose_name='cod')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrgrupp', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Група  - юзер',
                'verbose_name_plural': 'Група  - юзер',
                'db_table': 'priv',
            },
        ),
    ]
