# Generated by Django 4.2.7 on 2024-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenss',
            name='contragent',
            field=models.CharField(default=11, max_length=500, verbose_name='назва контрагента'),
            preserve_default=False,
        ),
    ]
