# Generated by Django 4.2.7 on 2024-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_licenss_contragent'),
    ]

    operations = [
        migrations.CreateModel(
            name='mg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mg', models.CharField(max_length=500, unique=True, verbose_name='mg')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('okpo', models.CharField(max_length=10, verbose_name='okpo')),
                ('contragent', models.CharField(max_length=500, verbose_name='назва контрагента')),
            ],
            options={
                'verbose_name': 'mg',
                'verbose_name_plural': 'mg',
                'db_table': 'mg',
            },
        ),
    ]
