# Generated by Django 4.2.7 on 2024-09-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mg',
            options={'verbose_name': 'пов', 'verbose_name_plural': 'пов'},
        ),
        migrations.AlterField(
            model_name='mg',
            name='mg',
            field=models.CharField(max_length=500, verbose_name='mg'),
        ),
    ]
