# Generated by Django 5.1.2 on 2024-12-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True)),
                ('inn', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=150)),
                ('nameK', models.CharField(max_length=150)),
                ('fatherly', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=500)),
                ('bankcard', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Працівники',
                'verbose_name_plural': 'Працівники',
                'db_table': 'employees',
            },
        ),
    ]
