# Generated by Django 5.1.2 on 2024-12-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='info',
            field=models.TextField(),
        ),
    ]
