# Generated by Django 5.1.2 on 2024-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_employees_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='bankcard',
            field=models.CharField(max_length=50, verbose_name='баківська картка'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='fatherly',
            field=models.CharField(max_length=150, verbose_name='по-батькові'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='info',
            field=models.TextField(verbose_name='інфо'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='inn',
            field=models.CharField(max_length=10, verbose_name='інн'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=500, verbose_name='найменування'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nameK',
            field=models.CharField(max_length=150, verbose_name='імя'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='фамілія'),
        ),
    ]
