# Generated by Django 5.1.2 on 2024-12-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_employees_bankcard_alter_employees_fatherly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='inn',
            field=models.CharField(max_length=10, unique=True, verbose_name='інн'),
        ),
    ]
