# Generated by Django 5.1.2 on 2025-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_employees_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='firma',
            field=models.TextField(default=1, verbose_name='Фірма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='info2',
            field=models.TextField(default=1, verbose_name='Контакти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='info3',
            field=models.TextField(default=1, verbose_name='Зарплата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='info4',
            field=models.TextField(default=1, verbose_name='Документи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='info',
            field=models.TextField(verbose_name='Загальне'),
        ),
    ]
