# Generated by Django 5.1.2 on 2025-01-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_employees_email_employees_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='phone_number',
        ),
    ]
