# Generated by Django 5.1.2 on 2025-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_employees_email_remove_employees_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='telefon'),
        ),
    ]
