# Generated by Django 5.1.2 on 2025-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_employees_email_employees_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=99, unique=True)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ціна')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Кількість')),
                ('sub1dt', models.CharField(max_length=99, verbose_name='Субконто1 Дт')),
                ('sub1kt', models.CharField(max_length=99, verbose_name='Субконто1 Кт')),
                ('info', models.TextField(verbose_name='Зміст')),
                ('accdt', models.CharField(max_length=8, verbose_name='Рахунок Дт')),
                ('acckt', models.CharField(max_length=8, verbose_name='Рахунок Кт')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводка',
                'db_table': 'posting',
            },
        ),
    ]
