# Generated by Django 5.1.2 on 2025-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='dat',
            field=models.CharField(default=1, max_length=99, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
