# Generated by Django 5.1.2 on 2025-01-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_posting_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='telefon'),
        ),
    ]
