# Generated by Django 4.2.7 on 2024-09-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Опис роботи')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('okpo', models.CharField(max_length=10, verbose_name='okpo')),
                ('contragent', models.CharField(max_length=500, verbose_name='назва контрагента')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Повідомлення виконавця')),
                ('status', models.CharField(max_length=10, verbose_name='статус')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата виконання')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'Order',
            },
        ),
    ]
