# Generated by Django 4.2.7 on 2024-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guid',
            field=models.CharField(default=1, max_length=99, unique=True, verbose_name='guid'),
            preserve_default=False,
        ),
    ]
