# Generated by Django 5.1.2 on 2025-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(default=1, max_length=99, verbose_name='тип документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='file_str',
            field=models.CharField(blank=True, max_length=500, verbose_name='урл файлика'),
        ),
        migrations.AddField(
            model_name='order',
            name='suma',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Сума'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_timestamp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дата виконання'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='статус'),
        ),
    ]
