# Generated by Django 5.1.2 on 2024-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_suma'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(default=1, max_length=99, verbose_name='тип документа'),
            preserve_default=False,
        ),
    ]
